# Generated by Django 5.2.12 on 2026-03-24 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dizimista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado')], max_length=20)),
                ('valor_primeira_contribuicao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField()),
                ('forma_pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('PIX', 'PIX'), ('Cartão de Débito', 'Cartão de Débito'), ('Cartão de Crédito', 'Cartão de Crédito')], max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('dizimista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='dizimo.dizimista')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
