# Generated by Django 5.1.5 on 2026-03-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dizimista',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Cônjuge'),
        ),
    ]
