# Generated by Django 5.1.5 on 2026-03-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dizimo', '0002_dizimista_nome_conjuge'),
    ]

    operations = [
        migrations.AddField(
            model_name='dizimista',
            name='numero_dizimista',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Dizimista'),
        ),
    ]
